version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    build: KeyfileMongo
    ports:
      - 27017:27017
    restart: always
  mongo1:
    hostname: mongo1
    container_name: mongo1
    build: KeyfileMongo
    ports:
      - 27018:27017
    restart: always
  mongo2:
    hostname: mongo2
    container_name: mongo2
    build: KeyfileMongo
    ports:
      - 27019:27017
    restart: always
  # creator:
  #   build: .
  #   entrypoint: ["mongo","--host","mongo0","--port","27017","--eval", 'rs.initiate( { _id : "rs0",members: [{ _id: 0, host: "mongo0:27017" },{ _id: 1, host: "mongo1:27017" },{ _id: 2, host: "mongo2:27017" }   ]})']
  #   depends_on:
  #     - mongo0
  #     - mongo1
  #     - mongo2